### ISSUE TITLE
Tracking Proposal #002: Existing VPC

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#306]
This is an umbrella issue is for tracking progress on custom VPC features as proposed in #303.

--- 

- [x] `--vpc-{private,public}-subnets` (initial baseline feature): #305
- [ ] `--vpc-id=default` (use default VPC and all of its existing subnets)
- [ ] `--vpc-id=default` with `--vpc-{private,public}-subnets` (use default VPC, but given subnet IDs)
- [ ] `--vpc-id="vpc-xxx"` (use given VPC, create dedicated subnets)
- [ ] `--vpc-id="vpc-xxx"` with `--vpc-{private,public}-subnets` (use given VPC ID, and given subnets - an explicit/logical option)
- [ ] `eksctl <create|get|delete> vpc --name=<vpcName>` (manage shared VPCs)
- [ ] `eksctl create cluster --vpc-name=<vpcName>` (create cluster in a shared VPC)

**Comment by mumoshu** [comment]
I love eksctl's ability to use pre-created subnets. Nice!

However, I'd suggest not to do this:

> --vpc-id="vpc-xxx" (use given VPC, create dedicated subnets)

This seems like a shoot-youself-in-the-foot. I've once encountered my kube-aws user who unintentionally created an unmovable, important AWS resource - RDS DB instance - in the subnet kube-aws has created and managed by CloudFormation. They can never destroy the cfn stack...

**Comment by martina-if** [comment]
Most of the things in this issue have been implemented or there are other issues for tracking them so I will close this one.
