### ISSUE TITLE
ensure all config fields that can be set are handled appropriately

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#425]
These include:

- [x] cluster AZs (https://github.com/weaveworks/eksctl/issues/420)
- [x] VPC ID (if set, don't need to lookup) (#447)
- [x] cluster SG (if set, don't need to create it) (part of #438)
- [x] nodegroup SGs (if set, don't need to create it) (#412 and #438, and #448 as a follow-up)
- [x] nodegroup IAM roles (also error on conflict with add-ons) (#450)
- [x] cluster service IAM role (#450)

**Comment by errordeveloper** [comment]
Re-opening, as nodegroup local SG always gets created, we need to find a sensible way to control this behaviour, which is probably best to do in v1alpha4.
