### ISSUE TITLE
cluster updates follow-up TODOs

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#608]
Here are the TODOs for the upcoming release:

- [x] documentation – #610
- [x] `eksctl utils update-kube-proxy` – #614
- [x] `eksctl utils update-aws-node` – #618
- [x] `eksctl utils install-coredns` – #630
- [x] `eksctl updates cluster --config-file/-f` – #628

Following items would be nice to have:
- `eksctl validate cluster` - this can be simple to begin with, e.g. check server and kubelet versions match up, run any existing checks
- turn `eksctl drain nodegroup --undo` to something more meaningful
- `eksctl updates cluster --version`

**Comment by errordeveloper** [comment]
This is done, 0.1.24 is out 🎉🌟
