### ISSUE TITLE
CloudFormation limitations

### ISSUE THREAD

**Issue by errordeveloper** [weaveworks/eksctl#778]
This issue is for tracking well-known limitation of CloudFormation that has affected eksctl in some way.

Long-standing:
- [x] cannot tag IAM resources (ref https://github.com/weaveworks/eksctl/issues/750)
- [ ] cannot tag EIP resources (ref https://github.com/weaveworks/eksctl/issues/751)
- [ ] cannot change main VPC route table (ref https://github.com/weaveworks/eksctl/issues/605)
- [ ] cannot tag EBS root volumes (ref #1030)

Present:
- [x] EKS logging (https://github.com/weaveworks/eksctl/issues/704) (using API)
- [ ] EKS endpoints (https://github.com/weaveworks/eksctl/issues/649)
- [ ] EKS upgrade bugs (see https://github.com/aws/containers-roadmap/issues/115#issuecomment-481376376)

Past:
- [x] EKS cluster version updates

**Comment by whereisaaron** [comment]
There’s an excellent roadmap project AWS is sharing to track the lagging support between AWS API changes and CF support.
https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap

**Comment by whereisaaron** [comment]
- VPC main route table: **_no issue raised on [CF coverage roadmap](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap)?_**
- IAM tags: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/19
- EBS root volume tags: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/133
- EIP tags: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/84

- EKS tags: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/200
- EKS logs: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/208
- EKS endpoints: https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/118
- EKS upgrade bugs: https://github.com/aws/containers-roadmap/issues/497

**Comment by whereisaaron** [comment]
It looks like IAM roles can now be tagged, is that all we need? https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-tags
```
Type: AWS::IAM::Role
Properties: 
  AssumeRolePolicyDocument: Json
  Description: String
  ManagedPolicyArns: 
    - String
  MaxSessionDuration: Integer
  Path: String
  PermissionsBoundary: String
  Policies: 
    - Policy
  RoleName: String
  Tags: 
    - Tag
```

**Comment by errordeveloper** [comment]
@whereisaaron yes, that would help, do they propagate stack tags also or only when explicitly set?

**Comment by whereisaaron** [comment]
@errordeveloper stack tag should propagate I think, if the docs are correct, but I have not tested.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-resource-tags.html
"All stack-level tags, including automatically created tags, are propagated to resources that AWS CloudFormation supports. Currently, tags are not propagated to Amazon EBS volumes that are created from block device mappings."

**Comment by jimsmith** [comment]
Hello,

Having deployed CF template using the IAM Roles 'tags' https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html#cfn-iam-role-tags

I have found that the `!Ref` is not being honored.

This below works when it's hardcoded
```
Tags:
        - 
          Key: "keyname1"
          Value: "value1"
        - 
          Key: "keyname2"
          Value: "value2"
```

This below is not working and the same Parameter works for EC2 and Lambda resources.

```
Tags:
        - Key: Application
          Value: !Ref 'Application'
        - Key: Application
          Value: !Ref 'Application'
```

**Comment by duckie** [comment]
It appears that CloudFormaton cannot tag EKS control planes either. It is overlooked because worked around as a post creation task. Still, it is definitely a limitation.
